os:
  - linux
language: node_js
node_js:
  - "10.14.1"
cache:
  directories:
    - $HOME/.npm
    - node_modules
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export CHROME_BIN=chromium-browser
install:
  - npm install
script:
  - npm run lint
  - npm test
  - npm run build

notifications:
  email: false
